"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Swal from "sweetalert2";
import "sweetalert2/dist/sweetalert2.min.css";
import styles from "./users.module.css";
import spacing from "./spacing.module.css";

type User = { id: number; name: string; email: string; role: string; status: string };
const roleNames: Record<string, string> = { admin: "ผู้ดูแลระบบ", teacher: "ครู", student: "นักเรียน", user: "ผู้ใช้งาน" };

export default function Users() {
  const [users, setUsers] = useState<User[]>([]); const [query, setQuery] = useState(""); const [role, setRole] = useState("all"); const [show, setShow] = useState(false); const [editing, setEditing] = useState<User | null>(null); const [saving, setSaving] = useState(false);
  const load = () => fetch("/api/users", { cache: "no-store" }).then((r) => r.json()).then((x) => Array.isArray(x) && setUsers(x));
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => users.filter((user) => (!query || `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase())) && (role === "all" || user.role === role)), [users, query, role]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const values = Object.fromEntries(new FormData(event.currentTarget)); const endpoint = editing ? `/api/users/${editing.id}` : "/api/users"; const response = await fetch(endpoint, { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); setSaving(false); if (!response.ok) { const result = await response.json().catch(() => ({})); Swal.fire({ icon: "error", title: "บันทึกไม่สำเร็จ", text: String(result.error ?? "กรุณาลองใหม่") }); return; } setShow(false); setEditing(null); await load(); Swal.fire({ icon: "success", title: editing ? "แก้ไขผู้ใช้แล้ว" : "เพิ่มผู้ใช้แล้ว", timer: 1200, showConfirmButton: false }); }
  async function remove(user: User) { const answer = await Swal.fire({ icon: "warning", title: `ลบ ${user.name}?`, text: "ข้อมูลผู้ใช้จะถูกลบออกจากระบบ", showCancelButton: true, confirmButtonText: "ลบ", cancelButtonText: "ยกเลิก", confirmButtonColor: "#dc3545" }); if (!answer.isConfirmed) return; const response = await fetch(`/api/users/${user.id}`, { method: "DELETE" }); if (response.ok) { await load(); Swal.fire({ icon: "success", title: "ลบผู้ใช้แล้ว", timer: 1200, showConfirmButton: false }); } }
  return <main className="content"><header><div><p className="eyebrow">ผู้ดูแลระบบ</p><h1>ผู้ใช้งาน</h1></div><button className="primary" onClick={() => { setEditing(null); setShow(!show); }}>เพิ่มผู้ใช้งาน</button></header><section><h2>จัดการผู้ใช้งาน</h2><p className="sub">กำหนดบทบาทและสถานะการใช้งานของสมาชิก</p></section>{(show || editing) && <form className={`card ${styles.form}`} onSubmit={save}><h2>{editing ? "แก้ไขผู้ใช้งาน" : "เพิ่มผู้ใช้งาน"}</h2><div className={styles.formGrid}><input name="name" defaultValue={editing?.name ?? ""} placeholder="ชื่อผู้ใช้งาน" required /><input name="email" type="email" defaultValue={editing?.email ?? ""} placeholder="อีเมล" required /><input name="password" type="password" placeholder={editing ? "รหัสผ่านใหม่ (ไม่เปลี่ยนเว้นว่าง)" : "รหัสผ่าน"} required={!editing} /><select name="role" defaultValue={editing?.role ?? "student"}><option value="student">นักเรียน</option><option value="teacher">ครู</option><option value="admin">ผู้ดูแลระบบ</option></select></div><button className="primary" disabled={saving}>{saving ? "กำลังบันทึก..." : "บันทึก"}</button></form>}
    <div className={styles.filters}><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ค้นหาชื่อหรืออีเมล" /><select value={role} onChange={(e) => setRole(e.target.value)}><option value="all">ทุกบทบาท</option><option value="student">นักเรียน</option><option value="teacher">ครู</option><option value="admin">ผู้ดูแลระบบ</option></select><button className="secondary-button" onClick={() => { setQuery(""); setRole("all"); }}>ค้นหา</button></div>
    <div className={styles.table}><div className={styles.head}><span>ชื่อผู้ใช้งาน</span><span>อีเมล</span><span>บทบาท</span><span>สถานะ</span><span>จัดการ</span></div>{filtered.map((user) => <div className={styles.row} key={user.id}><b>{user.name}</b><span>{user.email}</span><span><em className="status info">{roleNames[user.role] ?? user.role}</em></span><span><em className="status success">{user.status === "active" ? "ใช้งานอยู่" : user.status}</em></span><span className={styles.actions}><button className="detail-button" onClick={() => { setEditing(user); setShow(false); }}>แก้ไข</button><button className="delete-button" onClick={() => remove(user)}>ลบ</button></span></div>)}</div></main>;
}
