<x-app-layout>
    <x-slot name="header"><p class="text-xs font-medium tracking-wide text-slate-400">ผู้ดูแลระบบ</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-900">จัดการครุภัณฑ์</h2></x-slot>
    <div class="px-4 py-8 sm:px-8">
        @if (session('success'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{{ session('success') }}</div>@endif
        @if (session('error'))<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{{ session('error') }}</div>@endif
        <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="text-xl font-bold text-slate-900">รายการครุภัณฑ์</h1><p class="mt-1 text-sm text-slate-500">เพิ่ม แก้ไข และตรวจสอบข้อมูลครุภัณฑ์ในระบบ</p></div><a href="{{ route('admin.equipment.create') }}" class="ui-button-primary">เพิ่มครุภัณฑ์</a></div>
        <form class="ui-card mb-5 flex flex-col gap-3 p-4 sm:flex-row"><input name="search" value="{{ request('search') }}" placeholder="ค้นหาชื่อหรือรหัส" class="min-h-11 flex-1 px-3"><select name="status" class="min-h-11 px-3"><option value="">ทุกสถานะ</option>@foreach(['available'=>'พร้อมใช้งาน','borrowed'=>'กำลังยืม','maintenance'=>'กำลังซ่อม','damaged'=>'ชำรุด','disposed'=>'จำหน่ายแล้ว'] as $value=>$label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select><button class="ui-button-secondary">ค้นหา</button></form>
        <div class="ui-card overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-100 text-left"><th class="p-4">รหัส</th><th class="p-4">ชื่อครุภัณฑ์</th><th class="p-4">ประเภท</th><th class="p-4">สถานที่</th><th class="p-4">สถานะ</th><th class="p-4">จัดการ</th></tr></thead><tbody>@forelse($equipment as $item)<tr class="border-b border-slate-100 last:border-0"><td class="p-4 font-semibold text-slate-800">{{ $item->code }}</td><td class="p-4 text-slate-700">{{ $item->name }}</td><td class="p-4 text-slate-500">{{ $item->category?->name ?? '-' }}</td><td class="p-4 text-slate-500">{{ $item->location?->name ?? '-' }}</td><td class="p-4"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ match($item->status){'available'=>'bg-emerald-50 text-emerald-700','borrowed'=>'bg-blue-50 text-blue-700','maintenance'=>'bg-amber-50 text-amber-700','damaged'=>'bg-red-50 text-red-700',default=>'bg-slate-100 text-slate-600'} }}">{{ ['available'=>'พร้อมใช้งาน','borrowed'=>'กำลังยืม','maintenance'=>'กำลังซ่อม','damaged'=>'ชำรุด','disposed'=>'จำหน่ายแล้ว'][$item->status] ?? $item->status }}</span></td><td class="p-4"><div class="flex flex-wrap gap-2"><a href="{{ route('admin.equipment.show',$item) }}">ดู</a><a href="{{ route('admin.equipment.edit',$item) }}">แก้ไข</a><form method="POST" action="{{ route('admin.equipment.destroy',$item) }}" onsubmit="return confirm('ยืนยันการลบครุภัณฑ์นี้?')">@csrf @method('DELETE')<button>ลบ</button></form></div></td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-slate-400">ไม่พบข้อมูลครุภัณฑ์</td></tr>@endforelse</tbody></table></div></div><div class="mt-5">{{ $equipment->onEachSide(1)->links('vendor.pagination.minimal') }}</div>
    </div>
</x-app-layout>
