import type { Metadata } from "next";
import "./globals.css";
import "./responsive.css";
import "./font.css";

export const metadata: Metadata = {
  title: "School Assets",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="th" className="h-full antialiased">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
