<x-app-layout>
    <x-slot name="header"><p class="text-xs font-medium tracking-wide text-slate-400">ผู้ดูแลระบบ</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-900">ผู้ใช้งาน</h2></x-slot>
    <div class="px-4 py-8 sm:px-8">
        @if (session('success'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{{ session('success') }}</div>@endif
        @if (session('error'))<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{{ session('error') }}</div>@endif
        <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="text-xl font-bold text-slate-900">จัดการผู้ใช้งาน</h1><p class="mt-1 text-sm text-slate-500">กำหนดบทบาทและสถานะการใช้งานของสมาชิก</p></div><a href="{{ route('admin.users.create') }}" class="ui-button-primary">เพิ่มผู้ใช้งาน</a></div>
        <form class="ui-card mb-5 flex flex-col gap-3 p-4 sm:flex-row"><input name="search" value="{{ request('search') }}" placeholder="ค้นหาชื่อหรืออีเมล" class="min-h-11 flex-1 px-3"><select name="role" class="min-h-11 px-3"><option value="">ทุกบทบาท</option>@foreach(['admin'=>'ผู้ดูแลระบบ','teacher'=>'ครู','student'=>'นักเรียน'] as $value=>$label)<option value="{{ $value }}" @selected(request('role')===$value)>{{ $label }}</option>@endforeach</select><button class="ui-button-secondary">ค้นหา</button></form>
        <div class="ui-card overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-100 text-left"><th class="p-4">ชื่อผู้ใช้งาน</th><th class="p-4">อีเมล</th><th class="p-4">บทบาท</th><th class="p-4">สถานะ</th><th class="p-4">จัดการ</th></tr></thead><tbody>@forelse($users as $user)<tr class="border-b border-slate-100 last:border-0"><td class="p-4 font-semibold text-slate-800">{{ $user->name }}</td><td class="p-4 text-slate-500">{{ $user->email }}</td><td class="p-4"><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{{ ['admin'=>'ผู้ดูแลระบบ','teacher'=>'ครู','student'=>'นักเรียน'][$user->getRoleNames()->first()] ?? $user->getRoleNames()->first() ?? 'ยังไม่กำหนด' }}</span></td><td class="p-4"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $user->status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $user->status === 'active' ? 'ใช้งานอยู่' : 'ปิดใช้งาน' }}</span></td><td class="p-4"><div class="flex flex-wrap gap-2"><a href="{{ route('admin.users.edit',$user) }}">แก้ไข</a><form method="POST" action="{{ route('admin.users.destroy',$user) }}" onsubmit="return confirm('ยืนยันการลบผู้ใช้งานนี้?')">@csrf @method('DELETE')<button>ลบ</button></form></div></td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-400">ไม่พบข้อมูลผู้ใช้งาน</td></tr>@endforelse</tbody></table></div></div><div class="mt-5">{{ $users->onEachSide(1)->links('vendor.pagination.minimal') }}</div>
    </div>
</x-app-layout>
