<x-app-layout>
    <x-slot name="header"><p class="text-xs font-medium tracking-wide text-slate-400">การดูแลครุภัณฑ์</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-900">แจ้งซ่อมและบำรุงรักษา</h2></x-slot>
    <div class="px-4 py-8 sm:px-8">
        @if (session('success'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{{ session('success') }}</div>@endif
        <div class="mb-6"><h1 class="text-xl font-bold text-slate-900">งานซ่อมบำรุง</h1><p class="mt-1 text-sm text-slate-500">แจ้งปัญหาและติดตามความคืบหน้าการซ่อมครุภัณฑ์</p></div>
        <form method="POST" action="{{ route('maintenance.store') }}" class="ui-card mb-7 p-5 sm:p-6">@csrf<h3 class="font-bold text-slate-900">แจ้งปัญหาใหม่</h3><div class="mt-4 grid gap-4 md:grid-cols-3"><select name="equipment_id" class="min-h-11 px-3" required>@foreach(\App\Models\Equipment::whereNotIn('status',['disposed'])->get() as $e)<option value="{{ $e->id }}">{{ $e->code }} — {{ $e->name }}</option>@endforeach</select><input name="issue_description" required placeholder="อธิบายอาการหรือปัญหา" class="min-h-11 px-3 md:col-span-2"><button class="ui-button-primary md:col-span-3 md:w-fit">ส่งแจ้งซ่อม</button></div></form>
        <div class="space-y-3">@forelse($maintenances as $m)<article class="ui-card p-5"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p class="font-semibold text-slate-900">{{ $m->equipment->name }} <span class="ml-1 text-xs font-normal text-slate-400">{{ $m->equipment->code }}</span></p><p class="mt-2 text-sm text-slate-600">{{ $m->issue_description }}</p><p class="mt-3 text-xs text-slate-400">ผู้แจ้ง {{ $m->reporter->name }} · {{ $m->reported_date?->format('d/m/Y') }}</p></div><span class="w-fit rounded-full px-3 py-1 text-xs font-semibold {{ match($m->status){'completed'=>'bg-emerald-50 text-emerald-700','in_progress'=>'bg-blue-50 text-blue-700','cannot_repair'=>'bg-red-50 text-red-700',default=>'bg-amber-50 text-amber-700'} }}">{{ ['reported'=>'แจ้งแล้ว','in_progress'=>'กำลังซ่อม','completed'=>'ซ่อมเสร็จแล้ว','cannot_repair'=>'ซ่อมไม่ได้'][$m->status] ?? $m->status }}</span></div>@if(auth()->user()->hasRole('admin'))<form method="POST" action="{{ route('maintenance.update',$m) }}" class="mt-5 grid gap-2 border-t border-slate-100 pt-4 md:grid-cols-4">@csrf @method('PATCH')<select name="status" class="min-h-10 px-3"><option value="reported">แจ้งแล้ว</option><option value="in_progress" @selected($m->status==='in_progress')>กำลังซ่อม</option><option value="completed" @selected($m->status==='completed')>ซ่อมเสร็จแล้ว</option><option value="cannot_repair" @selected($m->status==='cannot_repair')>ซ่อมไม่ได้</option></select><input type="number" step="0.01" name="repair_cost" value="{{ $m->repair_cost }}" placeholder="ค่าใช้จ่าย" class="min-h-10 px-3"><input name="notes" value="{{ $m->notes }}" placeholder="หมายเหตุ" class="min-h-10 px-3 md:col-span-2"><button class="ui-button-secondary md:col-span-4 md:w-fit">บันทึกการอัปเดต</button></form>@endif</article>@empty<div class="ui-card p-10 text-center text-slate-400">ยังไม่มีรายการแจ้งซ่อม</div>@endforelse</div><div class="mt-5">{{ $maintenances->onEachSide(1)->links('vendor.pagination.minimal') }}</div>
    </div>
</x-app-layout>
